version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "4000:3000"
    restart: always
    env_file: .env
    depends_on:
      - database
    networks:
      - internal

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "8081:80"
    restart: always
    networks:
      - internal

  database:
    container_name: database
    image: postgres:12
    env_file: .env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: kupipodariday
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
